### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by cagallo** [Shared-Milk/shared-milk-ui#99]

**Comment by janitastic** [comment]
**Updates**

- [ ] **Code Architecture** - update to new count of components
- [ ] Do we want to add the BE Technologies too? Or just the FE since it's our readme?
- [ ] **Testing** Update testing instructions a bit to put them in order
- [ ] **Project Wins** - add error handling, and successful collaboration with BE
- [ ] **Future Iterations** - let's double check this with our project board wish list
